name: doxygen-ghpages
env:
  ISPN_VER: '13.0.5.Final'
on: [push, pull_request]
jobs:
  run-ci-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mattnotmitt/doxygen-action@v1.9.2
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.DOTNETCLIENT_PERSONAL_TOKEN }}
          publish_dir: ./docs
          external_repository: rigazilla/Infinispan.Hotrod.Core
